name: Update `development` branch

on:
  push:
    branches:
      - main

jobs:
  update-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - shell: bash
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git branch -f development
          git push -f origin development
